[docker]
configs = [
        "selenium/standalone-firefox:4.0.0-rc-2-prerelease-20210923", "{\"browserName\": \"firefox\"}",
        "selenium/standalone-chrome:4.0.0-rc-2-prerelease-20210923", "{\"browserName\": \"chrome\"}"
]
url = "http://172.17.0.1:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210923"
